# https://www.appveyor.com/docs/appveyor-yml/

image: Visual Studio 2017

version: 2.1.{build}

configuration: Release

clone_depth: 1

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SDK_URL: 'https://dotnetcli.azureedge.net/dotnet/Sdk/2.2.204/dotnet-sdk-2.2.204-win-x64.zip'

cache:
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

install:
- ps: >-
    $env:DOTNET_ROOT = "..\.dotnet"

    mkdir $env:DOTNET_ROOT -Force | Out-Null

    $env:DOTNET_ROOT = (Resolve-Path $env:DOTNET_ROOT)

    Invoke-WebRequest -Uri "$env:DOTNET_SDK_URL" -OutFile "$env:DOTNET_ROOT\dotnet-sdk.zip"
    
    Expand-Archive "$env:DOTNET_ROOT\dotnet-sdk.zip" "$env:DOTNET_ROOT"
    
    $env:PATH = "$env:DOTNET_ROOT;$env:Path"

build_script:
- cmd: call build.cmd

test_script:
- cmd: call test.cmd

artifacts:
- path: dotnet-xdt/bin/$(configuration)/*.nupkg
- path: dotnet-xdt/bin/$(configuration)/net461/dotnet-xdt.exe
  name: dotnet-xdt.exe
- path: dotnet-xdt.tests/bin/$(configuration)/net461/test-results.xml
  name: test-results/net461.xml
- path: dotnet-xdt.tests/bin/$(configuration)/netcoreapp2.1/test-results.xml
  name: test-results/netcoreapp21.xml

deploy: off