# https://www.appveyor.com/docs/appveyor-yml/

image: Visual Studio 2019 Preview

version: 2.2.{build}

configuration: Release

clone_depth: 1

environment:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SDK_URL: 'https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.401/dotnet-sdk-3.1.401-win-x64.zip'

cache:
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

install:
- ps: >-
    $env:DOTNET_ROOT = "..\.dotnet"

    mkdir $env:DOTNET_ROOT -Force | Out-Null

    $env:DOTNET_ROOT = (Resolve-Path $env:DOTNET_ROOT)

    Invoke-WebRequest -Uri "$env:DOTNET_SDK_URL" -OutFile "$env:DOTNET_ROOT\dotnet-sdk.zip"

    Expand-Archive "$env:DOTNET_ROOT\dotnet-sdk.zip" "$env:DOTNET_ROOT"

    $env:PATH = "$env:DOTNET_ROOT;$env:Path"

build_script:
- ps: ./build.ps1

test_script:
- ps: ./test.ps1

artifacts:
- path: dotnet-xdt/bin/$(configuration)/*.nupkg
- path: dotnet-xdt/bin/$(configuration)/net461/dotnet-xdt.exe
  name: dotnet-xdt.exe
- path: dotnet-xdt.tests/bin/$(configuration)/net48/test-results.xml
  name: test-results/net48.xml
- path: dotnet-xdt.tests/bin/$(configuration)/netcoreapp3.1/test-results.xml
  name: test-results/netcoreapp31.xml

deploy: off