image: Visual Studio 2017

version: 2.1.{build}

configuration: Release

clone_depth: 1

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  CLI_VERSION: 2.1.300

install:
- ps: >-
    $env:DOTNET_ROOT = "..\.dotnet"

    mkdir $env:DOTNET_ROOT -Force | Out-Null

    $env:DOTNET_ROOT = (Resolve-Path $env:DOTNET_ROOT)

    Invoke-WebRequest -Uri "https://download.microsoft.com/download/8/8/5/88544F33-836A-49A5-8B67-451C24709A8F/dotnet-sdk-2.1.300-win-x64.zip" -OutFile "$env:DOTNET_ROOT\dotnet-sdk.zip"
    
    Expand-Archive "$env:DOTNET_ROOT\dotnet-sdk.zip" "$env:DOTNET_ROOT"
    
    $env:PATH = "$env:DOTNET_ROOT;$env:Path"

build_script:
- ps: >-
    dotnet --version
    
    dotnet.exe msbuild dotnet-xdt /t:Restore /p:Configuration=Release /p:As=lib

    dotnet.exe msbuild dotnet-xdt /t:Pack    /p:Configuration=Release /p:As=lib

    dotnet.exe msbuild dotnet-xdt /t:Restore /p:Configuration=Release /p:As=tool

    dotnet.exe msbuild dotnet-xdt /t:Pack    /p:Configuration=Release /p:As=tool

    dotnet.exe msbuild dotnet-xdt /t:Restore /p:Configuration=Release /p:As=exe

    dotnet.exe msbuild dotnet-xdt /t:Build   /p:Configuration=Release /p:As=exe

test_script:
- ps: >-
    dotnet --version

    dotnet.exe restore /p:Configuration=Release

    cd dotnet-xdt.tests

    dotnet.exe fixie --configuration Release --report tests-results.xml

artifacts:
- path: dotnet-xdt/bin/Release/*.nupkg
- path: dotnet-xdt/bin/Release/**/*.exe
- path: dotnet-xdt.tests/**/tests-results.xml

deploy: off