image: Visual Studio 2017

version: 2.1.{build}

configuration: Release

clone_depth: 1

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  CLI_VERSION: 2.1.300

install:
- ps: >-
    $env:DOTNET_INSTALL_DIR = "..\.dotnet"

    mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
    
    Invoke-WebRequest -Uri "https://download.microsoft.com/download/8/8/5/88544F33-836A-49A5-8B67-451C24709A8F/dotnet-sdk-2.1.300-win-x64.zip" -OutFile dotnet-sdk.zip
    
    Expand-Archive dotnet-sdk.zip "$env:DOTNET_INSTALL_DIR"
    
    $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
- ps: >-
    dotnet --version
    
    dotnet.exe msbuild /t:Restore /p:Configuration=Release /p:Pack=lib

    dotnet.exe msbuild /t:Pack    /p:Configuration=Release /p:Pack=lib

    dotnet.exe msbuild /t:Restore /p:Configuration=Release /p:Pack=tool

    dotnet.exe msbuild /t:Pack    /p:Configuration=Release /p:Pack=tool

test_script:
- ps: >-
    cd dotnet-xdt.tests
    
    dotnet fixie --configuration Release --report dotnet-xdt.tests.xml

artifacts:
- path: dotnet-xdt/bin/**/*.nupkg

deploy: off