image: Visual Studio 2017

version: 2.1.{build}

configuration: Release

clone_depth: 1

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  CLI_VERSION: 2.1.0

install:
- ps: >-
    $env:DOTNET_INSTALL_DIR = "..\.dotnet"

    mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
    
    Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile "$($env:DOTNET_INSTALL_DIR)\dotnet-install.ps1"
    
    & "$($env:DOTNET_INSTALL_DIR)\dotnet-install.ps1" -Version $env:CLI_VERSION -InstallDir $env:DOTNET_INSTALL_DIR
    
    $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
- ps: >-
    dotnet --version
    
    dotnet.exe msbuild /t:Restore /p:Configuration=Release;Pack=lib

    dotnet.exe msbuild /t:Pack    /p:Configuration=Release;Pack=lib

    dotnet.exe msbuild /t:Restore /p:Configuration=Release;Pack=tool

    dotnet.exe msbuild /t:Pack    /p:Configuration=Release;Pack=tool

test_script:
- ps: >-
    cd dotnet-xdt.tests
    
    dotnet fixie --configuration Release --report dotnet-xdt.tests.xml

artifacts:
- path: dotnet-xdt/bin/**/*.nupkg

deploy: off