//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DotNet.Xdt.Tools.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DotNet.Xdt.Tools.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\AttributeFormatting_destination.bsl.
        /// </summary>
        public static string AttributeFormating_destination {
            get {
                return ResourceManager.GetString("AttributeFormating_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\AttributeFormatting_source.xml.
        /// </summary>
        public static string AttributeFormating_source {
            get {
                return ResourceManager.GetString("AttributeFormating_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\AttributeFormatting_transform.xml.
        /// </summary>
        public static string AttributeFormating_transform {
            get {
                return ResourceManager.GetString("AttributeFormating_transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\AttributeFormatting.Log.
        /// </summary>
        public static string AttributeFormatting_log {
            get {
                return ResourceManager.GetString("AttributeFormatting_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\EdgeCase_destination.bsl.
        /// </summary>
        public static string EdgeCase_destination {
            get {
                return ResourceManager.GetString("EdgeCase_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\EdgeCase.log.
        /// </summary>
        public static string EdgeCase_log {
            get {
                return ResourceManager.GetString("EdgeCase_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\EdgeCase_source.xml.
        /// </summary>
        public static string EdgeCase_source {
            get {
                return ResourceManager.GetString("EdgeCase_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\EdgeCase_transform.xml.
        /// </summary>
        public static string EdgeCase_transform {
            get {
                return ResourceManager.GetString("EdgeCase_transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\TagFormatting_destination.bsl.
        /// </summary>
        public static string TagFormatting_destination {
            get {
                return ResourceManager.GetString("TagFormatting_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\TagFormatting.log.
        /// </summary>
        public static string TagFormatting_log {
            get {
                return ResourceManager.GetString("TagFormatting_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\TagFormatting_source.xml.
        /// </summary>
        public static string TagFormatting_source {
            get {
                return ResourceManager.GetString("TagFormatting_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\TagFormatting_transform.xml.
        /// </summary>
        public static string TagFormatting_transform {
            get {
                return ResourceManager.GetString("TagFormatting_transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\WarningsAndErrors.log.
        /// </summary>
        public static string WarningsAndErrors_log {
            get {
                return ResourceManager.GetString("WarningsAndErrors_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\WarningsAndErrors_source.xml.
        /// </summary>
        public static string WarningsAndErrors_source {
            get {
                return ResourceManager.GetString("WarningsAndErrors_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\WarningsAndErrors_transform.xml.
        /// </summary>
        public static string WarningsAndErrors_transform {
            get {
                return ResourceManager.GetString("WarningsAndErrors_transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\Web.config.
        /// </summary>
        public static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..\Resources\Web.Release.config.
        /// </summary>
        public static string Web_Release {
            get {
                return ResourceManager.GetString("Web_Release", resourceCulture);
            }
        }
    }
}
